### ISSUE TITLE
Delay until Connection failed

### ISSUE THREAD

**Issue by salvq** [Heckie75/voltcraft-sem-3600bt#1]
Hi, thanks for great work / API and have an access to device. I am using Home Assistant to read the data however getting lot of Connection failed probably due to distance.

Currently I am pulling data from device every 60s and in average every 120s reading gets Connection failed. Where can I specify time delay until ERROR, I would like to increase time by few seconds to see if this helps.

Screenshot from command line:
```
pi@hassbian:/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt $ ./vc-sem.exp D0:39:72:BE:44:49 --on --status --json
ERROR:  Connection failed
pi@hassbian:/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt $ ./vc-sem.exp D0:39:72:BE:44:49 --on --status --json
ERROR:  Connection failed
pi@hassbian:/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt $ ./vc-sem.exp D0:39:72:BE:44:49 --on --status --json
{
  "device" : null,
  "status" : {
    "power" : 1,
    "voltage" : 238.4,
    "ampere" : 0.0,
    "watts" : 0.0,
    "frequency" : 49.96,
    "factor" : 1.0
  }
}
pi@hassbian:/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt $ ./vc-sem.exp D0:39:72:BE:44:49 --on --status --json
{
  "device" : null,
  "status" : {
    "power" : 1,
    "voltage" : 238.4,
    "ampere" : 0.0,
    "watts" : 0.0,
    "frequency" : 49.96,
    "factor" : 1.0
  }
}
pi@hassbian:/home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt $
```

**Comment by Heckie75** [comment]
Hi, you can try to change the timeout variable in line #37
This is the global timeout for expect.

**Comment by salvq** [comment]
Thanks for that, I did experiment with the timeout and also DELAY however did not help much to increase rate of success, mostly the issue is related to "Device or resource busy (16)" and not sure what is causing the device to be busy. Do you ? or how to find out why is busy, doing what ?

Thanks

```
pi@hassbian:~ $ /home/homeassistant/.homeassistant/custom_components/voltcraft-sem-3600bt/vc-sem.exp D0:39:72:BE:44:49 --debug --device
[                 ][LE]> connect D0:39:72:BE:44:49
Attempting to connect to D0:39:72:BE:44:49
Error: connect: Device or resource busy (16)
[D0:39:72:BE:44:49][LE]> ERROR: Connection failed
pi@hassbian:~ $
```

**Comment by Heckie75** [comment]
I have seen this kind of error before but not only related to this device. I guess it is related to poor bluetooth connections. Recently I have bought an external USB bluetooth adapter since the internal bluetooth device of my Intel NUC 2830 installed inside an aluminum case has extremely poor range. The new receiver works much better. Now I am able to control all playbulbs and bluetooth switches in all rooms of my flat. Connection errors are rarely. 

You can try to locate the switch closer to your PC just in order to find out if this kind of error is related to distance or poor range too.
